name: Build
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Packages
      run: |
        sudo apt-get update -y
        sudo apt-get install make wget unzip -y

    # Could've installed openjdk-17-headless, But it seems like
    # the runners have some old version of openjdk pre-installed
    # which causes conflicts
    - uses: actions/setup-java@v4
      with:
        distribution: "jetbrains"
        java-version: "17"

    - name: Setup Cache
      id: cache-sdk
      uses: actions/cache@v4
      with:
        path: sdk/
        key: ${{ runner.os }}-sdk

    - name: Setup Android SDK
      if: steps.cache-sdk.outputs.cache-hit != 'true'
      run: |
        chmod +x ./setup_android.sh
        mkdir sdk/
        cd sdk/
        ../setup_android.sh

    - name: Build (arm64-v8a)
      run: |
        make all -j4 \
          BUILD=build-arm64-v8a \
          TARGET_ARCH=arm64-v8a \
          ANDROID_SDK=./sdk/ \
          BUILD_TOOLS=./sdk/build-tools/36.0.0 \
          NDK=./sdk/ndk/27.2.12479018

    - name: Build (armeabi-v7a)
      run: |
        make all -j4 \
          BUILD=build-armeabi-v7a \
          TARGET_ARCH=armeabi-v7a \
          ANDROID_SDK=./sdk/ \
          BUILD_TOOLS=./sdk/build-tools/36.0.0 \
          NDK=./sdk/ndk/27.2.12479018

    - name: Build (x86)
      run: |
        make all -j4 \
          BUILD=build-x86 \
          TARGET_ARCH=x86 \
          ANDROID_SDK=./sdk/ \
          BUILD_TOOLS=./sdk/build-tools/36.0.0 \
          NDK=./sdk/ndk/27.2.12479018

    - name: Build (x86_64)
      run: |
        make all -j4 \
          BUILD=build-x86_64 \
          TARGET_ARCH=x86_64 \
          ANDROID_SDK=./sdk/ \
          BUILD_TOOLS=./sdk/build-tools/36.0.0 \
          NDK=./sdk/ndk/27.2.12479018

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-files
        if-no-files-found: error
        path: |
          ./build-arm64-v8a/*.apk
          ./build-armeabi-v7a/*.apk
          ./build-x86/*.apk
          ./build-x86_64/*.apk
