name: Build
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Deps (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install make openjdk-17-jdk-headless wget unzip -y

    - name: Setup Android SDK
      run: |
        mkdir sdk/
        cd sdk/
        sh ../setup_android.sh

    - name: Build
      run: |
        make all ANDROID_SDK=$(realpath ./sdk/)

    - name: Upload Artifacts (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        if-no-files-found: error
        path: ./build/
